package vn.aptech.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.0
 * 2024-04-01T16:48:05.669+07:00
 * Generated source version: 4.0.0
 *
 */
@WebServiceClient(name = "hello",
                  wsdlLocation = "http://localhost:8080/Day1_Hello/hello?wsdl",
                  targetNamespace = "http://ws.aptech.vn/")
public class Hello_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.aptech.vn/", "hello");
    public final static QName HelloPort = new QName("http://ws.aptech.vn/", "HelloPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/Day1_Hello/hello?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Hello_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/Day1_Hello/hello?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Hello_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Hello_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Hello_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public Hello_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public Hello_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public Hello_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns Hello
     */
    @WebEndpoint(name = "HelloPort")
    public Hello getHelloPort() {
        return super.getPort(HelloPort, Hello.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Hello
     */
    @WebEndpoint(name = "HelloPort")
    public Hello getHelloPort(WebServiceFeature... features) {
        return super.getPort(HelloPort, Hello.class, features);
    }

}
